# Generated by Django 3.0.3 on 2020-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20200421_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_explanation',
            new_name='transaction_description',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
