# Generated by Django 3.0.3 on 2020-04-24 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20200423_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_relevant_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referenceuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
